### PR TITLE
Exceptions thrown by MiddlewareContainer implements ContainerExceptionInterface

### LINKED ISSUE #573: V3 MiddlewareContainer is not PSR container compatible
`MiddlewareContainer::get()` throws `Exception\MissingDependencyException` and `Exception\InvalidMiddlewareException`. These exceptions imho should extend/implement [PSR exceptions](https://github.com/php-fig/container/blob/master/src/ContainerInterface.php#L23).

### PR DESCRIPTION
**Pull request by webimpress**
Fixes #573

### CODE REVIEW

File: test/ExceptionTest.php [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+        yield InvalidMiddlewareException::class => [InvalidMiddlewareException::class];
+        yield MissingDependencyException::class => [MissingDependencyException::class];
+    }
+
+    /**
+     * @dataProvider containerException
+     */
+    public function testExceptionIsInstanceOfContainerExceptionInterface(string $exception) : void
+    {
+        $this->assertTrue(is_a($exception, ContainerExceptionInterface::class, true));
```
Comment (webimpress) [inline test/ExceptionTest.php]: I think I'm too tired now, I don't know why `$this->assertInstanceOf` is not working here. Anyone can tell me please? :) Thx

Comment (webimpress) [reply test/ExceptionTest.php]: Ok, I know, both are `strings`...

**Comment by weierophinney** [comment]
Thanks, @webimpress.
